config/routes.rb
Rails.application.routes.draw do
  root "users#index"
  
  resources :borrowed_books
  resources :categories
  resources :users
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :category
end

app/models/borrowed_book.rb
class BorrowedBook < ApplicationRecord
    belongs_to :book
    belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :book
end

app/models/user.rb
class User < ApplicationRecord
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def application
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    def show
        @book = Book.find(params[:id])
    end

    def new
        @book = Book.new
    end

    def create
        @book = Book.new(book_params)
        if @book.save
            redirect_to root_path
        else
            render new
        end
    end

    def edit
        @book = Book.find(params[:id])
    end

    def update
        @book = Book.find(params[:id])
        @book.update(book_params)
        redirect_to root_path   
    end

    def destroy
        @book = Book.find(params[:id])
        @book.destroy
        redirect_to root_path
    end

    private
    def book_params
        params.require(:book).permit(:title, :category_id, :available)
    end
end

app/controllers/borrowed_books_controller.rb
class BorrowedBooksController < ApplicationController
    def show
        @books = Book.all
        @users = User.all
        @borrowed_books = BorrowedBook.all
    end
    def new
        @borrowed_book = BorrowedBook.new
    end
    def create
        @borrowed_book = BorrowedBook.new(borrow_book_params)
        if @borrowed_book.save
            Book.find(borrow_book_params[:book_id]).update(:available => false)
            redirect_to root_path

        else
            render new
        end
    end

    private
    def borrow_book_params
        params.require(:borrowed_book).permit(:user_id, :book_id)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def show
        @category = Category.find(params[:id])
        @books_by_category = Book.where(:category_id => @category.id)
    end

    def new
        @category = Category.new
    end

    def create
        @category = Category.new(category_params)
        if @category.save
            redirect_to root_path
        else
            render new
        end
    end

    def edit
        @category = Category.find(params[:id])
    end

    def update
        @category = Category.find(params[:id])
        @category.update(category_params)
        redirect_to root_path
        
    end

    def destroy
        @category = Category.find(params[:id])
        @category.destroy
        redirect_to root_path
    end

    private
    def category_params
        params.require(:category).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @categories = Category.all
    @books = Book.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path
    else
      render new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to users_path
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/borrowed_books_helper.rb
module BorrowedBooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<h2>New Book</h2>
<%= form_with model: @book do |form| %>
    <%= form.label :title, "Book Title"%><br>
    <%= form.text_field :title%><br>
    <%= form.label :category, "Category"%><br>
    <%= form.select :category_id, options_for_select(Category.all.pluck(:name, :id))%><br>
    <%= form.label :available, "Available"%><br>
    <%= form.radio_button :available, "true" %>
    <%= form.label :true, "True" %>
    <%= form.radio_button :available, "false" %>
    <%= form.label :false, "False" %><br>
    <%= form.submit %>
<% end %>

app/views/books/new.html.erb
<h2>New Book</h2>
<%= form_with model: @book do |form| %>
    <%= form.label :title, "Book Title"%><br>
    <%= form.text_field :title%><br>
    <%= form.label :category, "Category"%><br>
    <%= form.number_field :category_id, in: 1.0..20.0, step: 0.0 %><br>
    <%= form.label :available, "Available"%><br>
    <%= form.radio_button :true, "true" %>
    <%= form.label :true, "True" %>
    <%= form.radio_button :false, "false" %>
    <%= form.label :false, "False" %><br>
    <%= form.submit %>
<% end %>

app/views/books/show.html.erb
<h2>Category : <%= @book.category.name%></h2>
<h2>Title : <%= @book.title %></h2>
<h2>Availability : <%= @book.available%></h2>

app/views/borrowed_books/index.html.erb
<h1>Return Book</h1>

app/views/borrowed_books/new.html.erb
<h1>Borrow a Book</h1>
<%= form_with model: @borrowed_book do |form| %>
    <%= form.label :user_id, "Select User ID"%><br>
    <%= form.select :user_id, options_for_select(User.all.pluck(:name, :id))%><br>
    <%= form.label :book_id, "Select Book ID"%><br>
    <%= form.select :book_id, options_for_select(Book.all.pluck(:title, :id))%><br>
    <%= form.submit %>
<% end %>

app/views/borrowed_books/show.html.erb
<h1>Borrowed Books List</h1>
<%= link_to "Borrow a book", new_borrowed_book_path%>
<table>
    <tr>
        <th>Borrow ID</>
        <th>Book Title</>
        <th>User Name</>
        <th>Available</>
        <th>Action</>
    </tr>
    <% @borrowed_books.each do |borrowed_book|%>
    <tr>
        <td><%= borrowed_book.id%></td>
        <td><%= borrowed_book.book.title%></td>
        <td><%= borrowed_book.user.name%></td>
        <td><%= borrowed_book.book.available%></td>
        
    </tr>
    <% end %>
</table>

app/views/categories/_form.html.erb
<%= form_with model: @category do |form| %>
    <%= form.text_field :name, placeholder: "name" %>
    <%= form.submit %>
<% end %>

app/views/categories/edit.html.erb
<h3>Edit Category</h3>
<%= render partial: 'categories/form'%>

app/views/categories/new.html.erb
<h1>New Category</h1>
<%= render partial: 'categories/form'%>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<% @books_by_category.each do |book|%>
    <ul>
        <li><%= book.title%></li>
    </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GroundlabsBookeeper</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with model: @user do |form| %>
    <%= form.text_field :name, placeholder: "name" %>
    <%= form.submit %>
<% end %>

app/views/users/edit.html.erb
<h3>Edit User</h3>
<%= render partial: '/users/form' %>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Bookeeper Index</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
<div class="container">
    <h1>Users</h1>

    <%= link_to "Add New User", new_user_path, :class => "btn btn-success mar_bottom5"%>
    <table class="table">
        <tr>
            <th>ID</th>
            <th>User Name</th>
            <th>Action</th>
        </tr>
        <% @users.each do |user|%>
        <tr>
            <td><%= user.id%></td>
            <td><%= link_to user.name, user_path(user)%></td>
            <td><%= link_to "EDIT", edit_user_path(user.id)%>
            <%= link_to "DELETE", user_path(user), method: :delete, data:{confirm: "Are you sure?"}%></td>
        </tr>
        <% end %>
    </table>

    <br>

    <h1>Categories</h1>
    <%= link_to "Add New Category", new_category_path, :class => "btn btn-success mar_bottom5"%>
    <table class="table">
        <tr>
            <th>ID</th>
            <th>Category</th>
            <th>Action</th>
        </tr>
        <% @categories.each do |category|%>
        <tr>
            <td><%= category.id%></td>
            <td><%= link_to category.name, category_path(category)%></td>
            <td><%= link_to "EDIT", edit_category_path(category)%>
            <%= link_to "DELETE", category_path(category), method: :delete, data:{confirm: "Are you sure?"}%></td>
        </tr>
        <% end %>
    </table>
    <p>Note: Please click on Category Name to view books under each category.</p>

    <h1>Books</h1>
    <%= link_to "Add New Book", new_book_path, :class => "btn btn-success mar_bottom5"%>
    <table class="table">
        <tr>
            <th>ID</th>
            <th>Book Title</th>
            <th>Category No.</th>
            <th>Availability</th>
            <th>Action</th>
        </tr>
        <% @books.each do |book|%>
        <tr>
            <td><%= book.id%></td>
            <td><%= book.title%></td>
            <td><%= link_to book.category_id, book_path(book)%></td>
            <td><%= book.available%></td>
            <td><%= link_to "EDIT", edit_book_path(book)%>
            <%= link_to "DELETE", book_path(book), method: :delete, data:{confirm: "Are you sure?"}%>
            <%= link_to "BORROW", borrowed_book_path(book)%></td>
        </tr>
        <% end %>
    </table>
    <p>Note: Please click on Category No. to view category details.</p>
</div>
</body>
</html>

app/views/users/new.html.erb
<h3>New User</h3>
<%= render partial: '/users/form' %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>